### PR TITLE
Solar panel first prototype

### PR DESCRIPTION
**Pull request by SquidXTV**
# About
Solar panel upgrade for plane and large plane.
Automatically generates energy while using energy engine.
Gets better depending on the time etc.

## ToDo: 
* [x] Generating energy with energy engine
* [x] Textures and models for solar panel (plane, large plane and item)
* [x] Recipe

### CODE REVIEW

**Review by przemykomo — COMMENTED** [review]
I don't think it should be removed with the engine. It should just stay there not doing anything.

**Comment by SquidXTV** [comment]
okay gonna remove that

**Comment by SquidXTV** [comment]
should I also change upgrading it
currently its disabled if the plane got no electric engine

**Comment by przemykomo** [comment]
Yeah I think you should be able to add a solar panel without the engine.

**Comment by SquidXTV** [comment]
I think the only missing stuff is

1. new texture for item
2. new models
3. better recipe

and I'm not going to do texture/models stuff cause I'm not talented in that area

**Pull request merged**
