### PR TITLE
Flip

### PR DESCRIPTION
**Pull request by adoxentor**
Adds the banner and folding upgrades.
Allows plane to flip and roll.
New plane crush.
It is working, but maybe some beta testing is required, I fixed the all the bugs I found.

### CODE REVIEW

**Comment by przemykomo** [comment]
It works great, but I found these bugs:

- Non-player entities aren't rotated with plane.
- Plane doesn't crush if I fall on ground.
- First person view doesn't rotate (we could try do something at EntityViewRenderEvent.CameraSetup event)
- Banners on large planes are rendered like they would be on small plane (which is in incorrect position)

Also it looks for me like the planes are way too fast.
I didn't notice anything other than that.

**Comment by adoxentor** [comment]
try it now

**Comment by adoxentor** [comment]
fixed and updated the branch

**Comment by przemykomo** [comment]
There is only one bug left I found - second passenger in large plane is rendered too low.
screenshot

**Pull request merged**
